## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    if not bld.env['ENABLE_EXAMPLES']:
        return;

    obj = bld.create_ns3_program('main-simple',
                                 ['network', 'internet', 'applications'])
    obj.source = 'main-simple.cc'

    obj = bld.create_ns3_program('ipv4-raw-socket',
                                 ['network', 'internet', 'point-to-point', 'applications'])
    obj.source = 'ipv4-raw-socket.cc'
